spring.application.name=blog
server.port=8000
server.max-http-header-size = 400000 
# ??? ??? ?? ???  ???? 8K
#????
#oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe
spring.datasource.username=blog
spring.datasource.password=1234
## jpa
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
#Hibernate? DB? ??????.
spring.jpa.show-sql=true
#??, ???????? ?????????????.
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database=oracle

upload.file.path=C:/upload/

# ???
kakao.oauth.client-id=${kakaoRestApiKey}
kakao.oauth.redirect-uri=http://localhost:8000/login/oauth2/code/kakao
kakao.oauth.token-uri=https://kauth.kakao.com/oauth/token
kakao.oauth.user-info-uri=https://kapi.kakao.com/v2/user/me

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri=${GOOGLE_REDIRECT_URI}

# ???? ??
springdoc.sweager-ui.path = /swagger-ui.html
springdoc.api-docs.path=/v1/api-docs
springdoc.writer-with-order-by-keys=true

springdoc.info.title= Our Board API Project
springdoc.info.version=v1.0.0
springdoc.info.description = 게시판 및 회원 관리 서비스 API 문서

jwt.secret-key=${JWT_SECRET_KEY}

# Actuator
management.endpoints.web.exposure.include=prometheus,health,info

# Grafana
management.metrics.tags.application=blog

logging.level.com.example.demo=DEBUG